set -g mouse off
bind-key -n C-f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
set -g update-environment "DISPLAY SSH_AUTH_SOCK SSH_AGENT_PID DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR WAYLAND_DISPLAY"
set -g set-clipboard external

set -g base-index 1
setw -g pane-base-index 1

set -ga terminal-overrides ",*:Tc"

set -g status on

set -g status-style "fg=#b8b8c0,bg=#181818"
set -g status-justify left
set -g status-position bottom
set -g status-left-length 20
set -g status-right-length 20
set -g status-left " #S "
set -g status-right " %H:%M "

set -g window-status-format " #I:#W "
set -g window-status-current-format " [#I:#W]"

set -g pane-border-style "fg=#4c4c58"
set -g pane-active-border-style "fg=#8b8b99"
setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "wl-copy"
